-- SAE Forum Service — DDL Schema
-- Execute this script to create or recreate all tables from scratch.
-- The application uses ddl-auto=update so Hibernate manages this automatically.

CREATE TABLE IF NOT EXISTS FORUM_QUESTION (
    ID             BIGSERIAL PRIMARY KEY,
    TITULO         VARCHAR(200) NOT NULL,
    DESCRICAO      TEXT NOT NULL,
    TAGS           VARCHAR(500),
    AREA           VARCHAR(100),
    QUESTION_TYPE  VARCHAR(20) NOT NULL,
    STATUS         VARCHAR(20) NOT NULL DEFAULT 'ABERTA',
    CREATED_BY     VARCHAR(100) NOT NULL,
    CREATED_AT     TIMESTAMP NOT NULL,
    UPDATED_AT     TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_question_area   ON FORUM_QUESTION (AREA);
CREATE INDEX IF NOT EXISTS idx_question_status ON FORUM_QUESTION (STATUS);
CREATE INDEX IF NOT EXISTS idx_question_type   ON FORUM_QUESTION (QUESTION_TYPE);

CREATE TABLE IF NOT EXISTS EXPERT_ANSWER (
    ID          BIGSERIAL PRIMARY KEY,
    CONTEUDO    TEXT NOT NULL,
    QUESTION_ID BIGINT NOT NULL,
    ANSWERED_BY VARCHAR(100) NOT NULL,
    ACCEPTED    BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT  TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_expert_answer_question ON EXPERT_ANSWER (QUESTION_ID);

CREATE TABLE IF NOT EXISTS COLLABORATIVE_ANSWER (
    ID                BIGSERIAL PRIMARY KEY,
    CONTEUDO          TEXT NOT NULL,
    QUESTION_ID       BIGINT NOT NULL,
    ANSWERED_BY       VARCHAR(100) NOT NULL,
    VALIDATION_STATUS VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
    VALIDATED_BY      VARCHAR(100),
    VALIDATED_AT      TIMESTAMP,
    REJECTED_BY       VARCHAR(100),
    REJECTED_AT       TIMESTAMP,
    CREATED_AT        TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_collab_answer_question ON COLLABORATIVE_ANSWER (QUESTION_ID);
CREATE INDEX IF NOT EXISTS idx_collab_answer_status   ON COLLABORATIVE_ANSWER (VALIDATION_STATUS);
