server:
  port: 8081

spring:
  application:
    name: sae-auth-service
  profiles:
    active: dev
  
  # Configurações Comuns de Mail (Gmail)
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectompe@gmail.com
    password: twjbgqlyqlfjt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  jackson:
    date-format: yyyy-MM-dd

smartsae:
  security:
    allowed-origin: "*"
