-- alter session set "_ORACLE_SCRIPT"=true; 
-------------------------
-- 1 . SELECIONAR PROFILE
-------------------------
CREATE PROFILE SECURE LIMIT
PRIVATE_SGA UNLIMITED
SESSIONS_PER_USER UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
IDLE_TIME UNLIMITED
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
PASSWORD_LIFE_TIME 60
PASSWORD_GRACE_TIME 20
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 3;
-------------------------------------------------
-- 2. CRIACAO DAS TABLESPACES
-------------------------------------------------
CREATE BIGFILE TABLESPACE smartSAE_DATA DATAFILE '+DG_DATA' SIZE 10G AUTOEXTEND ON NEXT 10G MAXSIZE 280G LOGGING
DEFAULT COMPRESS FOR OLTP EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE BIGFILE TABLESPACE smartSAE_INDEX DATAFILE '+DG_DATA' SIZE 10G AUTOEXTEND ON NEXT 10G MAXSIZE 175G
LOGGING DEFAULT COMPRESS FOR OLTP
EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE BIGFILE TABLESPACE smartSAE_LOB DATAFILE '+DG_DATA' SIZE 50G AUTOEXTEND ON NEXT 10G MAXSIZE 300G LOGGING
DEFAULT COMPRESS FOR OLTP EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
--------------------------------------------------
-- 3. CRIACAO DAS ROLES
-------------------------------------------------
CREATE ROLE smartSAEUSERROLE;
CREATE ROLE smartSAEROLE;
--------------------------------------------------
-- 4. CRIACAO DO ESQUEMA / USERS
--------------------------------------------------
CREATE USER smartSAE
IDENTIFIED BY smartSAE
DEFAULT TABLESPACE smartSAE_DATA
TEMPORARY TABLESPACE TEMP
PROFILE SECURE
ACCOUNT UNLOCK; 

CREATE USER smartSAEUSER
IDENTIFIED BY smartSAE
DEFAULT TABLESPACE smartSAE_DATA
TEMPORARY TABLESPACE TEMP
PROFILE SECURE
ACCOUNT UNLOCK; 
--------------------------------------------------
-- 5. ROLES PARA smartSAE/smartSAEUSER
--------------------------------------------------
GRANT smartSAEROLE TO smartSAE; 
GRANT smartSAEUSERROLE TO smartSAEUSER; 

GRANT CONNECT TO smartSAE;
GRANT CONNECT TO smartSAEUSER;
 
GRANT RESOURCE TO smartSAE;

ALTER USER smartSAE DEFAULT ROLE ALL;  
ALTER USER smartSAEUSER DEFAULT ROLE ALL; 

REVOKE UNLIMITED TABLESPACE FROM smartSAE;
-------------------------------------------------
-- 6. System Privileges for smartSAEROLE/smartSAEUSERROLE 
-------------------------------------------------- 
GRANT CREATE VIEW TO smartSAEROLE; 
GRANT CREATE ANY SYNONYM TO smartSAEROLE;
GRANT CREATE MATERIALIZED VIEW TO smartSAEROLE;
GRANT DROP any SYNONYM TO smartSAEROLE; 
GRANT ANALYZE ANY TO smartSAEROLE;

GRANT ANALYZE ANY TO smartSAEUSERROLE;
GRANT ALTER ANY MATERIALIZED VIEW TO smartSAEUSERROLE;
-------------------------------------------------
-- 7. Tablespace Quotas for smartSAE
------------------------------------------------- 
ALTER USER smartSAE QUOTA UNLIMITED ON smartSAE_DATA; 
ALTER USER smartSAE QUOTA UNLIMITED ON smartSAE_LOB; 
ALTER USER smartSAE QUOTA UNLIMITED ON smartSAE_INDEX; 
-------------------------------------------------
-- 8. Object Privileges for smartSAE
-------------------------------------------------
GRANT EXECUTE ON SYS.DBMS_STATS TO smartSAEUSER;
GRANT EXECUTE ON SYS.DBMS_XA TO smartSAEUSER;
GRANT SELECT ON PENDING_TRANS$ TO smartSAEUSER;
GRANT SELECT ON DBA_2PC_PENDING TO smartSAEUSER;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO smartSAEUSER;
