--ALTER TABLE smartSAE_USER ADD ROLE VARCHAR2(64);
--UPDATE smartSAE_USER SET ROLE=PERMISSIONS;
--COMMIT;
-- ALTER TABLE smartSAE_USER DROP (
-- 	ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, VALIDATED, VALIDATION_METHOD, VALIDATION_TOKEN, PERMISSIONS);

-- iteracao do usuario na aplicacao 
CREATE TABLE smartSAE.APP_TRANSACTION (
	ID NUMBER(38) NOT NULL,
   	STATUS NUMBER(1) NOT NULL,
    CODE VARCHAR2(64) NOT NULL,
    TYPE VARCHAR2(64) NOT NULL,
	LABEL VARCHAR2(256) NOT NULL,
	ROUTER_LINK VARCHAR2(256),
	POSITION NUMBER(38) NOT NULL,
	PARENT_ID NUMBER(38),

	CONSTRAINT PK_APP_TRANSACTION PRIMARY KEY (ID),
  	CONSTRAINT TC_APP_TRANSACTION_STATUS CHECK (STATUS IN (0,1)),
  	CONSTRAINT FK_APP_TRANSACTION_01 FOREIGN KEY (PARENT_ID) REFERENCES smartSAE.APP_TRANSACTION(ID)
);

CREATE SEQUENCE smartSAE.APP_TRANSACTION_SEQUENCE START WITH 100 INCREMENT BY 1 NOCACHE;
-- CREATE OR REPLACE SYNONYM smartSAEUSER.APP_TRANSACTION FOR smartSAE.APP_TRANSACTION;
-- CREATE OR REPLACE SYNONYM smartSAEUSER.APP_TRANSACTION_SEQUENCE FOR smartSAE.APP_TRANSACTION_SEQUENCE;


GRANT SELECT, UPDATE, INSERT ON smartSAE.APP_TRANSACTION TO smartSAEUSERROLE;
GRANT SELECT ON smartSAE.APP_TRANSACTION_SEQUENCE TO smartSAEUSERROLE;

-- role da transacao do usuario
CREATE TABLE smartSAE.ROLE_TRANSACTION (
	ID NUMBER(38) NOT NULL,
   	STATUS NUMBER(1) NOT NULL,
    ROLE VARCHAR2(64) NOT NULL,
	APP_TRANSACTION_ID NUMBER(38),
	
	CONSTRAINT PK_ROLE_TRANSACTION PRIMARY KEY (ID),
  	CONSTRAINT TC_ROLE_TRANSACTION_STATUS CHECK (STATUS IN (0,1)),
  	CONSTRAINT FK_ROLE_TRANSACTION_01 FOREIGN KEY (APP_TRANSACTION_ID) REFERENCES smartSAE.APP_TRANSACTION(ID)
);

CREATE SEQUENCE smartSAE.ROLE_TRANSACTION_SEQUENCE START WITH 100 INCREMENT BY 1 NOCACHE;
-- CREATE OR REPLACE SYNONYM smartSAEUSER.ROLE_TRANSACTION FOR smartSAE.ROLE_TRANSACTION;
-- CREATE OR REPLACE SYNONYM smartSAEUSER.ROLE_TRANSACTION_SEQUENCE FOR smartSAE.ROLE_TRANSACTION_SEQUENCE;
-- GRANT SELECT, UPDATE, INSERT ON smartSAE.ROLE_TRANSACTION TO smartSAEUSERROLE;
-- GRANT SELECT ON smartSAE.ROLE_TRANSACTION_SEQUENCE TO smartSAEUSERROLE;

-- insercoes para app transaction
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (1, '01', 'HEADER', 'Agendamentos', null, 1.0, null, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (2, '0101', 'MENU_ITEM', 'Painel', '/admin/painel-tecnico', 1, 1, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (3, '0102', 'MENU_ITEM', 'Configurar Calendário ', '/admin/configurar-calendario', 2, 1, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (4, '0103', 'MENU_ITEM', 'Solicitar Agendamentos', '/admin/solicitar-agendamentos', 3, 1, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (5, '0104', 'MENU_ITEM', 'Solicitar Reagendamentos', '/admin/solicitar-reagendamentos', 4, 1, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (6, '0105', 'MENU_ITEM', 'Listar Agendamentos', '/admin/listar-agendamentos', 5, 1, 1);

-- INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (7, '02', 'HEADER', 'Catálogo', null, 2.0, null, 1);
-- INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (8, '0201', 'MENU_ITEM', 'Registar Proposta de Item', '/admin/registar-proposta-item', 1, 7, 1);

-- INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (9, '03', 'HEADER', 'Preços de Referência', null, 3.0, null, 1);
-- INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (10, '0301', 'MENU_ITEM', 'Registar Preço de Referência', '/admin/registar-preco-referencia', 1, 9, 1);

INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (11, '04', 'HEADER', 'Utilizadores', null, 4, null, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (12, '0401', 'MENU_ITEM', 'Consultar', '/admin/consultar-utilizadores', 1, 11, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (13, '0402', 'MENU_ITEM', 'Cadastrar', '/admin/cadastrar-utilizador', 2, 11, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (14, '0403', 'MENU_ITEM', 'Trocar Senha', '/admin/trocar-senha', 3, 11, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (14, '0404', 'MENU_ITEM', 'Promover', '/admin/promover-utilizadores', 4, 11, 1);

 --configurar canlendario
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (15, '05', 'HEADER', 'Manter Calendario', null, 5, null, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (16, '0501', 'MENU_ITEM', 'Configurar Calendario', '/admin/configurar-calendario', 1, 15, 1);



INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (17, '0502', 'MENU_ITEM', 'Cancelar Agendamentos', '/admin/cancelar-agendamento', 1, 1, 1);
INSERT INTO smartSAE.APP_TRANSACTION(ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS) VALUES (18, '0503', 'MENU_ITEM', 'Listar Agendamentos', '/admin/consultar-todos-agendamentos', 2, 1, 1);



 

-- insercoes para o role transaction
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='01'), 1);   
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0502'), 1); 
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0503'), 1); 

-- INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='02'), 1);
-- INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0201'), 1);
-- INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='03'), 1);
-- INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0301'), 1);
--INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='04'), 1); 




INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='05'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'EMBASSY_TECHNICIAN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0501'), 1);



INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'SCHEDULE_APPLICANT', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='01'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'SCHEDULE_APPLICANT', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0103'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'SCHEDULE_APPLICANT', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0104'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'SCHEDULE_APPLICANT', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0105'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'SCHEDULE_APPLICANT', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0403'), 1);


INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'ADMIN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='04'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'ADMIN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0401'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'ADMIN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0402'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'ADMIN', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0403'), 1);


INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'USER', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='04'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'USER', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0401'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'USER', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0402'), 1);
INSERT INTO smartSAE.ROLE_TRANSACTION(ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (smartSAE.ROLE_TRANSACTION_SEQUENCE.NEXTVAL, 'USER', (SELECT ID FROM smartSAE.APP_TRANSACTION WHERE CODE='0403'), 1);




