-- alter session set "_ORACLE_SCRIPT"=true; 
-------------------------
-- 1 . SELECIONAR PROFILE
-------------------------
CREATE PROFILE SECURE LIMIT
PRIVATE_SGA UNLIMITED
SESSIONS_PER_USER UNLIMITED
LOGICAL_READS_PER_SESSION UNLIMITED
LOGICAL_READS_PER_CALL UNLIMITED
IDLE_TIME UNLIMITED
CPU_PER_SESSION UNLIMITED
CPU_PER_CALL UNLIMITED
CONNECT_TIME UNLIMITED
PASSWORD_LIFE_TIME 60
PASSWORD_GRACE_TIME 20
FAILED_LOGIN_ATTEMPTS 3
PASSWORD_LOCK_TIME 3;
-------------------------------------------------
-- 2. CRIACAO DAS TABLESPACES
-------------------------------------------------
CREATE BIGFILE TABLESPACE smartsae_DATA DATAFILE '+DG_DATA' SIZE 10G AUTOEXTEND ON NEXT 10G MAXSIZE 280G LOGGING
DEFAULT COMPRESS FOR OLTP EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE BIGFILE TABLESPACE smartsae_INDEX DATAFILE '+DG_DATA' SIZE 10G AUTOEXTEND ON NEXT 10G MAXSIZE 175G
LOGGING DEFAULT COMPRESS FOR OLTP
EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE BIGFILE TABLESPACE smartsae_LOB DATAFILE '+DG_DATA' SIZE 50G AUTOEXTEND ON NEXT 10G MAXSIZE 300G LOGGING
DEFAULT COMPRESS FOR OLTP EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;
--------------------------------------------------
-- 3. CRIACAO DAS ROLES
-------------------------------------------------
CREATE ROLE smartsaeUSERROLE;
CREATE ROLE smartsaeROLE;
--------------------------------------------------
-- 4. CRIACAO DO ESQUEMA / USERS
--------------------------------------------------
CREATE USER smartsae
IDENTIFIED BY smartsae
DEFAULT TABLESPACE smartsae_DATA
TEMPORARY TABLESPACE TEMP
PROFILE SECURE
ACCOUNT UNLOCK; 

CREATE USER smartsaeUSER
IDENTIFIED BY smartsae
DEFAULT TABLESPACE smartsae_DATA
TEMPORARY TABLESPACE TEMP
PROFILE SECURE
ACCOUNT UNLOCK; 
--------------------------------------------------
-- 5. ROLES PARA smartsae/smartsaeUSER
--------------------------------------------------
GRANT smartsaeROLE TO smartsae; 
GRANT smartsaeUSERROLE TO smartsaeUSER; 

GRANT CONNECT TO smartsae;
GRANT CONNECT TO smartsaeUSER;
 
GRANT RESOURCE TO smartsae;

ALTER USER smartsae DEFAULT ROLE ALL;  
ALTER USER smartsaeUSER DEFAULT ROLE ALL; 

REVOKE UNLIMITED TABLESPACE FROM smartsae;
-------------------------------------------------
-- 6. System Privileges for smartsaeROLE/smartsaeUSERROLE 
-------------------------------------------------- 
GRANT CREATE VIEW TO smartsaeROLE; 
GRANT CREATE ANY SYNONYM TO smartsaeROLE;
GRANT CREATE MATERIALIZED VIEW TO smartsaeROLE;
GRANT DROP any SYNONYM TO smartsaeROLE; 
GRANT ANALYZE ANY TO smartsaeROLE;

GRANT ANALYZE ANY TO smartsaeUSERROLE;
GRANT ALTER ANY MATERIALIZED VIEW TO smartsaeUSERROLE;
-------------------------------------------------
-- 7. Tablespace Quotas for smartsae
------------------------------------------------- 
ALTER USER smartsae QUOTA UNLIMITED ON smartsae_DATA; 
ALTER USER smartsae QUOTA UNLIMITED ON smartsae_LOB; 
ALTER USER smartsae QUOTA UNLIMITED ON smartsae_INDEX; 
-------------------------------------------------
-- 8. Object Privileges for smartsae
-------------------------------------------------
GRANT EXECUTE ON SYS.DBMS_STATS TO smartsaeUSER;
GRANT EXECUTE ON SYS.DBMS_XA TO smartsaeUSER;
GRANT SELECT ON PENDING_TRANS$ TO smartsaeUSER;
GRANT SELECT ON DBA_2PC_PENDING TO smartsaeUSER;
GRANT SELECT ON DBA_PENDING_TRANSACTIONS TO smartsaeUSER;
