server:
  port: 8080

spring:
  application:
    name: sae-api-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods: ["GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS"]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
        # - id: sae-ai-service
        #   uri: http://localhost:8085
        #   predicates:
        #     - Path=/ai/**
