server:
  port: 8082

spring:
  application:
    name: sae-content-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/sae_content

smartsae:
  security:
    allowed-origin: "*"
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: admin123
    bucket: sae-contents
  pdfbox:
    temp-dir: ${java.io.tmpdir}/pdfbox
