spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://sae-postgres:5432/sae_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:mongo}:${MONGODB_PASSWORD:mongo123}@sae-mongodb:27017/sae_content?authSource=admin
      auto-index-creation: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      "[mail.smtp.auth]": true
      "[mail.smtp.starttls.enable]": true

smartsae:
  security:
    allowed-origin: "${FRONTEND_URL:*}"
  minio:
    endpoint: http://sae-minio:9000
    access-key: ${MINIO_ACCESS_KEY:admin}
    secret-key: ${MINIO_SECRET_KEY:admin123}
    bucket: sae-contents
  rabbitmq:
    host: sae-rabbitmq
    port: 5672
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
