spring:
  config:
    activate:
      on-profile: docker
  application:
    name: sae-ai-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
