-- -----------------------------------------------------------------------------
-- APP_TRANSACTION TABLE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS APP_TRANSACTION (
    ID BIGSERIAL PRIMARY KEY,
    STATUS SMALLINT NOT NULL DEFAULT 1,
    CODE VARCHAR(64) NOT NULL UNIQUE,
    TYPE VARCHAR(64) NOT NULL,
    LABEL VARCHAR(256) NOT NULL,
    ROUTER_LINK VARCHAR(256),
    POSITION BIGINT NOT NULL,
    PARENT_ID BIGINT REFERENCES APP_TRANSACTION(ID)
);

-- -----------------------------------------------------------------------------
-- ROLE_TRANSACTION TABLE
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ROLE_TRANSACTION (
    ID BIGSERIAL PRIMARY KEY,
    STATUS SMALLINT NOT NULL DEFAULT 1,
    ROLE VARCHAR(64) NOT NULL,
    APP_TRANSACTION_ID BIGINT REFERENCES APP_TRANSACTION(ID)
);

-- -----------------------------------------------------------------------------
-- SCHEMA ADJUSTMENTS
-- -----------------------------------------------------------------------------
-- Drop and recreate the check constraint to include 'GUEST' and other roles
-- This ensures that the enumeration in the database matches the UserRoles enum in Java.
ALTER TABLE ROLE_TRANSACTION DROP CONSTRAINT IF EXISTS role_transaction_role_check;
ALTER TABLE ROLE_TRANSACTION ADD CONSTRAINT role_transaction_role_check 
CHECK (ROLE IN ('ADMIN', 'STUDENT', 'PROFESSOR', 'ROOT', 'GUEST'));

-- -----------------------------------------------------------------------------
-- DATA SEEDING
-- -----------------------------------------------------------------------------

-- ROOT Header & Items
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (1, '01', 'HEADER', 'Sistema (Root)', NULL, 1, NULL, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (2, '0101', 'MENU_ITEM', 'Configurações de Rede', '/root/settings', 1, 1, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (3, '0102', 'MENU_ITEM', 'Gestão de Administradores', '/root/admins', 2, 1, 1) ON CONFLICT (ID) DO NOTHING;

-- ADMIN Header & Items
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (10, '02', 'HEADER', 'Gestão Académica', NULL, 2, NULL, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (11, '0201', 'MENU_ITEM', 'Escolas', '/admin/schools', 1, 10, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (12, '0202', 'MENU_ITEM', 'Turmas e Grades', '/admin/classrooms', 2, 10, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (13, '0203', 'MENU_ITEM', 'Disciplinas', '/admin/subjects', 3, 10, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (14, '0204', 'MENU_ITEM', 'Utilizadores', '/admin/users', 4, 10, 1) ON CONFLICT (ID) DO NOTHING;

-- PROFESSOR Header & Items
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (20, '03', 'HEADER', 'Área do Professor', NULL, 3, NULL, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (21, '0301', 'MENU_ITEM', 'Painel de Respostas', '/professor/dashboard', 1, 20, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (22, '0302', 'MENU_ITEM', 'Minhas Turmas', '/professor/my-classes', 2, 20, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (23, '0303', 'MENU_ITEM', 'Meus Alunos', '/professor/students', 3, 20, 1) ON CONFLICT (ID) DO NOTHING;

-- STUDENT Header & Items
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (30, '04', 'HEADER', 'Área do Aluno', NULL, 4, NULL, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (31, '0401', 'MENU_ITEM', 'Meus Estudos', '/student/dashboard', 1, 30, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (32, '0402', 'MENU_ITEM', 'Dúvidas e Perguntas', '/student/questions', 2, 30, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (33, '0403', 'MENU_ITEM', 'Biblioteca Digital', '/student/library', 3, 30, 1) ON CONFLICT (ID) DO NOTHING;

-- GUEST Header & Items
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (40, '05', 'HEADER', 'Início', NULL, 5, NULL, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO APP_TRANSACTION (ID, CODE, TYPE, LABEL, ROUTER_LINK, POSITION, PARENT_ID, STATUS)
VALUES (41, '0501', 'MENU_ITEM', 'Biblioteca Digital', '/student/library', 1, 40, 1) ON CONFLICT (ID) DO NOTHING;

-- Map Roles to Transactions
-- ROOT
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (1, 'ROOT', 1, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (2, 'ROOT', 2, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (3, 'ROOT', 3, 1) ON CONFLICT (ID) DO NOTHING;
-- ADMIN
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (10, 'ADMIN', 10, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (11, 'ADMIN', 11, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (12, 'ADMIN', 12, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (13, 'ADMIN', 13, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (14, 'ADMIN', 14, 1) ON CONFLICT (ID) DO NOTHING;
-- PROFESSOR
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (20, 'PROFESSOR', 20, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (21, 'PROFESSOR', 21, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (22, 'PROFESSOR', 22, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (23, 'PROFESSOR', 23, 1) ON CONFLICT (ID) DO NOTHING;
-- STUDENT
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (30, 'STUDENT', 30, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (31, 'STUDENT', 31, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (32, 'STUDENT', 32, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (33, 'STUDENT', 33, 1) ON CONFLICT (ID) DO NOTHING;
-- GUEST
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (40, 'GUEST', 40, 1) ON CONFLICT (ID) DO NOTHING;
INSERT INTO ROLE_TRANSACTION (ID, ROLE, APP_TRANSACTION_ID, STATUS) VALUES (41, 'GUEST', 41, 1) ON CONFLICT (ID) DO NOTHING;

-- Synchronize sequences if IDs were hardcoded
SELECT setval('app_transaction_id_seq', (SELECT MAX(id) FROM app_transaction));
SELECT setval('role_transaction_id_seq', (SELECT MAX(id) FROM role_transaction));
