spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://sae-postgres:5432/sae_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

content:
  service:
    url: http://sae-content-service:8082

quiz:
  academic-service:
    url: http://sae-academic-service:8085

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
