#
# Copyright (c) 2003-2016 . All rights reserved.
#
project.debug=true
project.compile.source=1.8
project.compile.target=1.8

javadoc.skip=true
skipTests=true

dist.version=SNAPSHOT
dist.overwrite=true

artifact.name=smartsae-api
# Sera a mesma da $artifact.name porem com apenas a segunda parte.
build.label=01.00.00

remote.server=172.31.4.99
remote.username=jbossadm
remote.password=utrafe123
remote.jbossapp.dir=/opt/jbossapp

remote.delivery.server=172.31.4.99
remote.delivery.username=jbossadm
remote.delivery.password=utrafe123

server.mode=standalone
deployments.dir=/opt/jbossapp/wildfly/standalone/deployments