version: '3.8'

services:
  # Base de Dados Relacional (PostgreSQL)
  postgres:
    image: postgres:15
    container_name: sae-postgres
    environment:
      - POSTGRES_DB=sae_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - sae-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Base de Dados Documental (MongoDB)
  mongodb:
    image: mongo:latest
    container_name: sae-mongodb
    ports:
      - "27017:27017"
    networks:
      - sae-network
    volumes:
      - mongodb_data:/data/db

  # Camada de Cache (Redis)
  redis:
    image: redis:alpine
    container_name: sae-redis
    ports:
      - "6379:6379"
    networks:
      - sae-network

  # Object Storage (MinIO)
  minio:
    image: minio/minio
    container_name: sae-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - sae-network
  # Microserviços
  # sae-auth-service:
  #   build: ./sae-auth-service
  #   container_name: sae-auth-service
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sae_db
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #     - SPRING_DATA_REDIS_HOST=redis
  #   depends_on:
  #     - postgres
  #     - redis
  #   networks:
  #     - sae-network

  # sae-content-service:
  #   build: ./sae-content-service
  #   container_name: sae-content-service
  #   ports:
  #     - "8082:8082"
  #   environment:
  #     - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/sae_content
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - sae-network

  # sae-forum-service:
  #   build: ./sae-forum-service
  #   container_name: sae-forum-service
  #   ports:
  #     - "8083:8083"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/sae_db
  #     - SPRING_DATASOURCE_USERNAME=postgres
  #     - SPRING_DATASOURCE_PASSWORD=postgres
  #   depends_on:
  #     - postgres
  #   networks:
  #     - sae-network

  # sae-api-gateway:
  #   build: ./sae-api-gateway
  #   container_name: sae-api-gateway
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - sae-auth-service
  #   networks:
  #     - sae-network

networks:
  sae-network:
    driver: bridge

volumes:
  postgres_data:
  mongodb_data:
  minio_data:
